#!/bin/sh
#
### BEGIN INIT INFO
# Provides: weston
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

killproc() {
	all_pids=`/bin/pidof $1`

	# busybox pidof doesn't ommit the current pid
	# as this script is called weston on the target
	# in thinlinux with a busybox based utility load
	# later killproc operations end up killing this
	# script.
	for pid in $all_pids
	do
		if [ "$pid" != "$$" ]; then
			kill_pids+=$pid
		fi
	done

	[ "$kill_pids" != "" ] && kill $kill_pids
}

read CMDLINE < /proc/cmdline
for x in $CMDLINE; do
        case $x in
        weston=false)
		echo "Weston disabled"
		exit 0;
                ;;
        esac
done

case "$1" in
  start)
        . /etc/profile

        # Weston for some reason dies if these environment variables are set
        unset WAYLAND_DISPLAY

        # This is all a nasty hack
        if test -z "$XDG_RUNTIME_DIR"; then
            export XDG_RUNTIME_DIR=/run/user/root
        fi

        if [ ! -d "$XDG_RUNTIME_DIR" ] ; then
            mkdir --parents $XDG_RUNTIME_DIR
            chmod 0700 $XDG_RUNTIME_DIR
        fi

        echo "Starting Weston"

        if [ ! -d "/dev/input" ]; then
            echo "Waiting for input device..."
            killproc weston
            sleep 3
        fi

        openvt -c 4 -f runWeston
  ;;

  stop)
        echo "Stopping Weston"
        killproc weston
  ;;

  restart)
	$0 stop
        sleep 2
        $0 start
  ;;

  *)
        echo "usage: $0 { start | stop | restart }"
  ;;
esac

exit 0
